# Generated by Django 4.1.1 on 2022-09-25 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_patientdata_time_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='time',
            field=models.TimeField(max_length=100, verbose_name=datetime.time(15, 56, 6, 809126)),
        ),
    ]
