# Generated by Django 4.1.1 on 2022-09-25 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_patientdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='mobile',
            field=models.IntegerField(default=1986554),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='time',
            field=models.TimeField(max_length=100, verbose_name=datetime.time(1, 41, 29, 759447)),
        ),
    ]
