# Generated by Django 4.1.1 on 2022-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientquery',
            name='image',
        ),
        migrations.AddField(
            model_name='patientquery',
            name='qrimage',
            field=models.ImageField(default='default.jpg', upload_to='images/qrcode'),
        ),
    ]
