# Generated by Django 4.1.1 on 2022-09-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_patientquery_image_patientquery_qrimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientquery',
            old_name='query',
            new_name='problem',
        ),
    ]
