# Generated by Django 4.1.1 on 2022-09-26 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_prescription_delete_patientdatadoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='time',
            field=models.TimeField(max_length=100, verbose_name=datetime.time(21, 58, 18, 994752)),
        ),
    ]
